using ArrDash.Models;

namespace ArrDash.Tests.Infrastructure;

internal static class PreferencesTestFactory
{
    public static UserLayoutPreferences CreateFullyPopulated() => new()
    {
        Theme = ThemePreference.Dark,
        KioskMode = true,
        DashboardTitle = "Test title",
        DashboardSubtitle = "Test subtitle",
        PosterSize = PosterSize.Large,
        PosterPlacement = PosterPlacement.Top,
        DefaultRecentLimit = 42,
        PanelOrder = ["recent-music", "recent-tv"],
        PanelViewModes = { ["recent-tv"] = PanelViewMode.Table },
        PanelCollapsed = { ["recent-movies"] = true },
        PanelRolledUp = { ["recent-tv"] = true },
        PanelAccentColors = { ["recent-tv"] = "#112233" },
        RecentLimits = { ["recent-tv"] = 33 },
        Density = LayoutDensity.Compact,
        HideHeroStrip = true,
        StatusBarMode = StatusBarMode.OfflineOnly,
        TimeFormat = TimeDisplayFormat.DateTime,
        RecentWindowMode = RecentWindowMode.Days,
        RecentDays = 14,
        AudiobookSource = AudiobookSourceMode.ChaptarrOnly,
        ShowPlexSessions = false,
        ShowEmbySessions = false,
        HideIdleSessions = true,
        ShowServerMetrics = false,
        EnableClickThrough = false,
        DeepLinkClickThrough = false,
        ExternalLinkTarget = ExternalLinkTarget.SameTab,
        MissingEpisodeClickAction = MissingEpisodeClickAction.OpenSonarrAndSearch,
        FriendlyQualityLabels = false,
        PrimaryColor = "#aabbcc",
        SecondaryColor = "#ddeeff",
        ButtonColor = "#123456",
        LightTextColor = "#111111",
        DarkTextColor = "#eeeeee",
        LightBackgroundColor = "#fafafa",
        DarkBackgroundColor = "#101010",
        LightSurfaceColor = "#ffffff",
        DarkSurfaceColor = "#202020",
        LightAppBarColor = "#303030",
        DarkAppBarColor = "#404040",
        GradientStartColor = "#505050",
        GradientEndColor = "#606060",
        BackgroundStyle = BackgroundStyle.Solid,
        BrandMark = "XY",
        BorderRadius = BorderRadiusStyle.Sharp,
        ShowQuality = false,
        ShowEpisodeBadges = false,
        ShowMissingEpisodes = false,
        ShowSyncNotes = false,
        PollIntervalSeconds = 120,
        MetricsPollIntervalSeconds = 5,
        MetricsGraphWindowMinutes = 30,
        NetworkPieChartSize = 220,
        NetworkPieStyle = NetworkPieStyle.Glossy,
        NetworkPieShowSliceLabels = false,
        NetworkLegendShowPercent = true,
        NetworkLegendShowRate = true,
        NetworkLegendShowCpu = true,
        ManualRefreshOnly = true,
        StartupPage = StartupPage.Settings,
        ServiceEnabled = { ["sonarr"] = false },
        AutoKioskOnLoad = true,
        KioskHideHero = false,
        KioskLargeNowPlaying = true,
        KioskScreensaver = true,
        KioskScreensaverMinutes = 10,
        KioskRotate = KioskRotateMode.Sequential,
        KioskRotateSeconds = 45,
        ShowSettingsHelp = true
    };

    public static DownloadItem CreateTvItem(int daysAgo, int episode = 1) => new(
        Id: $"tv-{daysAgo}-{episode}",
        Source: MediaSource.Sonarr,
        MediaType: MediaType.Tv,
        Title: $"Show {daysAgo}",
        Subtitle: null,
        Event: DownloadEvent.Imported,
        Timestamp: DateTimeOffset.UtcNow.AddDays(-daysAgo),
        PosterUrl: null,
        Quality: "WEBDL-1080p",
        SizeBytes: null,
        SeasonNumber: 1,
        EpisodeNumbers: [episode]);
}
